# Generated by Django 4.2.6 on 2023-11-06 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume_', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
